stages:
  - build
  - deploy

default:
  image: node:20-alpine

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mkdir -p public && cp -r dist/* public/
  artifacts:
    paths:
      - public
  environment:
    name: production
    url: https://byunes-group.gitlab.io/traiteur
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
